services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    container_name: majelan_test_mysql
    volumes:
      - mysql-data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data:
